# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubBrowser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubBrowser
  pod 'OctoKit'
  pod 'SwiftyUserDefaults'
  pod 'AlamofireObjectMapper'
  pod 'SDWebImage'
  pod 'KeychainAccess'
  pod 'SVProgressHUD'
  
  target 'GithubBrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubBrowserUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
